project_id = "xlmvlplazxrouscupidi"

[functions.ai-chat]
verify_jwt = false

[functions.generate-command]
verify_jwt = false

[functions.generate-music]
verify_jwt = false

[functions.template-assistant]
verify_jwt = false

[functions.validate-api-key]
verify_jwt = false

[functions.compile-arduino]
verify_jwt = false

[functions.ai-explain-symbol]
verify_jwt = false

[functions.ai-generate-tests]
verify_jwt = false

[functions.session-recorder-sync]
verify_jwt = false

[functions.manage-env-secrets]
verify_jwt = false
